[package]
name = "verified-pt"
version = "0.1.0"
edition = "2021"

[dependencies]
vstd = { version = "0.0.0-2025-08-12-1837", default-features = false }
bitflags = "2.1"

[features]
usermode = []
easy = []
aarch64 = []